### ISSUE TITLE
Assumptions about `KUBERNETES_SERVICE_HOST` break kubecf

### ISSUE THREAD

**Issue by viovanov** [cloudfoundry/capi-k8s-release#107]
There are new code paths in the cloud controller that assume that if the CC is deployed on Kubernetes, Diego is no longer used.

e.g. https://github.com/cloudfoundry/cloud_controller_ng/blob/ce3d1a021552668d727d8793ce27fd93bf77ba57/lib/vcap/config.rb#L12

This breaks KubeCF, as it supports both Diego and Eirini.

**Comment by viovanov** [comment]
cc @jandubois

**Comment by tcdowney** [comment]
Thanks for logging this! Copying over some context [from Slack](https://cloudfoundry.slack.com/archives/C017LDM6KTQ/p1605731267374900):

```
viovanov  21 hours ago
it would be useful to control these new code paths using config flags or something

matt-royal  19 hours ago
The rub there is that the schema is set before we load the config file, which is why we leaned on environment variables. We may just have to load the yaml without a schema, read it, set the schema, then re-read it.
```

**Comment by matt-royal** [comment]
@viovanov The simplest solution here would be to look for a kubecf-specific environment variable, and revert to the cf-for-vms config schema if we're on kuberntes, but that variable is set.

If that isn't an option, then I believe I have a solution that chooses the schema based on the presence of the `kubernetes` key in the config file. That solution is more complicated, though, so I'd prefer the first solution if possible.

**Comment by matt-royal** [comment]
I made a few attempts at the solution I mentioned above (i.e. changing the schema based on the presence of the `kubernetes` key). Unfortunately I don't think this is possible without significant changes to how we define and enforce the config schema. My two attempts were both failures and were very difficult to read.

Hopefully there's an environment variable we can use to detect kubecf and we can solve this using that.

**Comment by jandubois** [comment]
> Hopefully there's an environment variable we can use to detect kubecf and we can solve this using that.

There isn't one right now, afaict, but maybe Quarks could add one automatically, @viovanov ?

I guess we could also add one from kubecf itself, using ops files to add bosh agent settings, but having a global setting that is automatically applied to all pods managed by quarks seems preferable to me.

**Comment by matt-royal** [comment]
[This commit](https://github.com/cloudfoundry/cloud_controller_ng/commit/54e904855e866ed8abc408377db33940ad55a802) changed how cloud controller chooses which config schema to use. It now uses the presence of the `kpack.host_url` key to decide between the Kubernetes or Vms schemas. Hopefully that will resolve the issue for kubecf. I'm going to optimistically close this issue, but please reopen if there are still problems after you integrate this change.
