### ISSUE TITLE
STRICT Istio mesh mTLS policy is incompatible with Cloud Controller's init container

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/capi-k8s-release#12]
## Background
When `STRICT` mode is enabled for the mTLS Istio mesh policy all traffic between Pods covered by the policy _must_ use mTLS. This means that the Istio sidecars (`istio-proxy` Envoy container) must be ready before Pods can successfully communicate with each other over the network. See the [Istio Security docs](https://istio.io/docs/concepts/security/#mutual-tls-authentication) for much information all of this.

The issue with Cloud Controller right now is that it is using an [init container to run database migrations](https://github.com/cloudfoundry/capi-k8s-release/blob/1bc5ea5eac9359af22fb2088c21a27f5a4b356aa/templates/api_server_deployment.yml#L25-L31). This init container runs before the regular `istio-proxy` container on the Pod is ready so there is no client sidecar in place to mediate the mTLS connection with the sidecar running on the database Pod<sup>1</sup>.

Currently there is no workaround on the Istio side. Their stance<sup>2</sup> is:

> There is no easy solution. Your init container will run before the sidecar starts. If your container runs before Istio’s init container it will not be secure. If your container runs after Istio’s it will not have network access.
>
> If you can avoid doing network I/O in your init containers you should. If you must use init containers that expect connectivity, you’ll need a work-around.

Can Cloud Controller run these migrations in some other way? Maybe in a [Job](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/)?

Thanks!
Tim && @ndhanushkodi

### Footnotes
**<sup>1</sup>** this actually probably doesn't matter for off cluster databases 🤔💭 
**<sup>2</sup>** https://discuss.istio.io/t/k8s-istio-sidecar-injection-with-other-init-containers/845

**Comment by cwlbraa** [comment]
https://www.pivotaltracker.com/n/projects/966314/stories/171394866 is the real story to solve this permanently 👍

**Comment by aashah** [comment]
The attached story for this work https://www.pivotaltracker.com/story/show/171388449 (alongside the related work around running DB migrations separately) has been completed. I'm going to close this issue out, but please let me know if there's something missing.

There's currently some CI problems, so I'm not fully sure when all the work will make it to capi-k8s-release and cf-for-k8s.
