### ISSUE TITLE
Cloud Controller deployment names should start with `cloud-controller` instead of `capi`

### ISSUE THREAD

**Issue by emalm** [cloudfoundry/capi-k8s-release#15]
It is confusing that the Cloud Controller deployments ([API](https://github.com/cloudfoundry/capi-k8s-release/blob/master/templates/api_server_deployment.yml), [generic worker](https://github.com/cloudfoundry/capi-k8s-release/blob/master/templates/worker_deployment.yml), [clock](https://github.com/cloudfoundry/capi-k8s-release/blob/master/templates/clock_deployment.yml), and [deployment updater](https://github.com/cloudfoundry/capi-k8s-release/blob/master/templates/deployment_updater_deployment.yml)) are prefixed with `capi-` instead of with `cloud-controller-` or something similar, as [Cloud Controller](https://github.com/cloudfoundry/cloud_controller_ng) is the component that they run.

These names also do not match the corresponding job names in the CAPI BOSH release ([`cloud_controller_ng`](https://github.com/cloudfoundry/capi-release/tree/1.91.0/jobs/cloud_controller_ng), [`cloud_controller_worker`](https://github.com/cloudfoundry/capi-release/tree/1.91.0/jobs/cloud_controller_worker), [`cloud_controller_clock`](https://github.com/cloudfoundry/capi-release/tree/1.91.0/jobs/cloud_controller_clock), and [`cc_deployment_updater`](https://github.com/cloudfoundry/capi-release/tree/1.91.0/jobs/cc_deployment_updater)). Additionally, "CAPI" in a Kubernetes context now typically means the [Cluster API](https://github.com/kubernetes-sigs/cluster-api), so including `capi` in the names of these deployments is likely to confuse those already familiar with Kubernetes projects.

Finally, these names should be changed sooner rather than later, before consumers such as cf-for-k8s begin to provide backwards compatibility or high reliability to their users.

**Comment by selzoc** [comment]
Would it make more sense to be `cf-api`?  Also I feel like our service should also be renamed.

**Comment by emalm** [comment]
@selzoc so what would the complete names of the deployments be? `cf-api-{server,worker,clock,deployment-updater}`? In that case, I'd still be concerned that the name isn't descriptive enough, as CC isn't the only API presented publicly in CF, although I suppose you could get away with it through the convention that `api.$SYSTEM_DOMAIN` is the default external subdomain for CC and the intent for CC's `/` endpoint to be the point of discovery discovery for any associated APIs such as UAA or log-cache.

I do appreciate @ssisil's [concern](https://www.pivotaltracker.com/story/show/171663717/comments/212253412) that there's also a naming collision between CF's Cloud Controller and the K8s [Cloud Controller Manager](https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/), but at least the CC name is specific about which CF component is running inside the deployment pods.

👍 to renaming the associated K8s service similarly.

**Comment by cwlbraa** [comment]
All of our API documentation has always presented CC's api as "The Cloud Foundry API,"  and when at least when I go looking for those API docs, that's what I search for. 

It's certainly true that CC's API isn't the only API in CF, but calling something "The Cloud Foundry API" doesn't necessarily imply to folks that it's the _only_ API. 

That said, maybe some additional descriptor would help- REST?

**Comment by aashah** [comment]
I added this to our tech forum this week, hopefully we can get a decision then to change this while we minimally can.

**Comment by selzoc** [comment]
We ratified in tech forum today that the `cf-api` prefix seems to fit the best and we'll prioritize this soon 👍

**Comment by aashah** [comment]
This is now in cf-for-k8s. closing this out.
