### ISSUE TITLE
Kpack naming/tagging strategy

### ISSUE THREAD

**Issue by nthomson-pivotal** [cloudfoundry/capi-k8s-release#19]
Raising by request of @selzoc 

As it is currently implemented, the kpack integration uses a naming strategy whereby multiple `push`es of a single application will each result in unique images being created in the image repository, rather than creating separate tags of the same image.

For example, pushing an app twice might currently create:

```
library/78f0dcd6-2d8d-464e-8094-e95926dabac3:b1.20200316.233450
library/2ce2458d-0ef0-43f0-929a-b9dd2c106e54:b1.20200316.232455
```

instead of:

```
library/2ce2458d-0ef0-43f0-929a-b9dd2c106e54:b1.20200316.232455
library/2ce2458d-0ef0-43f0-929a-b9dd2c106e54:b2.20200316.233450
```

The strategy taken here should be chosen very deliberately, as there could be consequences related to broader tooling, for example:

1. In Harbor this creates a separate repository for every single push, how will this scale?
2. Image scanning tools may provide a user experience assuming a tag per app version, and creating a separate image could create headache for users of this tooling
3. Various container registries could have limitations which are exacerbated by not using tags, leading to cost or maintenance implications

This is not to say the current approach is wrong, but that it should be carefully weighed against alternatives.

**Comment by cppforlife** [comment]
+1 on reusing image repositories _at least_ for the same app. i could even see it being extended to single image repository for all apps, under which individual apps get unique tags.

**Comment by selzoc** [comment]
Here is the story we're going to use to implement this behavior: https://www.pivotaltracker.com/story/show/171851581

**Comment by aashah** [comment]
Hello,

We recently pushed a fix for this in cloud_controller_ng. Should be available in capi-k8s-release -> cf-for-k8s soon.

closing this out. please feel free to re-open or comment if there is more discussion!

thanks,
Aakash
