### ISSUE TITLE
Kpack Staging pod is created in the system namespace

### ISSUE THREAD

**Issue by alex-slynko** [cloudfoundry/capi-k8s-release#21]
System and user components should live in different namespaces to simplify security (for example with Networking policies).
Right now, the staging pod is created in cf-system namespace.

**Comment by selzoc** [comment]
Which namespace seems more appropriate?  `cf-workloads`?

**Comment by alex-slynko** [comment]
I think `cf-workloads` is the right place for staging.

**Comment by selzoc** [comment]
Fixed by https://github.com/cloudfoundry/capi-k8s-release/commit/685f10eadf7d767ccd977ec773b672e68154ccf5
