### ISSUE TITLE
Kpack build CRD and pod stay in cf-system namespace after the application is deleted

### ISSUE THREAD

**Issue by alex-slynko** [cloudfoundry/capi-k8s-release#22]
Steps to reproduce:

1. cf push with broken staging (ie wrong repository)
1. cf delete app

Expected:

No strange pods in the staging namespace

Actual:

Leftover pod from staging + leftover build object with "Failed" status

**Comment by selzoc** [comment]
I'm curious what your opinion is on how long the build resource and pod should stick around even in the case of a successful build?  Currently it seems like they stick around forever.

**Comment by alex-slynko** [comment]
I am not sure when they should get deleted in normal cases but after the application is deleted there should be no `build` objects.

**Comment by selzoc** [comment]
I checked in with the `kpack` team and how many failed/succeeded builds stick around [is configurable](https://github.com/pivotal/kpack/blob/master/docs/image.md):

```
failedBuildHistoryLimit: The maximum number of failed builds for an image that will be retained.
successBuildHistoryLimit: The maximum number of successful builds for an image that will be retained.
```

I do agree that once an app is deleted, all the related resources should also be deleted.

**Comment by selzoc** [comment]
Made a more complete story to take care of this: https://www.pivotaltracker.com/story/show/171900207

**Comment by aashah** [comment]
Hello,

@sethboyles and I just finished the story. After it's been accepted, we'll look into getting it bumped in capi-k8s-release & cf-for-k8s.

**Comment by aashah** [comment]
Hello,

I just bumped CCNG's docker image in capi-k8s-release to include the work for this issue.

I am waiting to bump capi-k8s-release in cf-for-k8s on a separate story (https://www.pivotaltracker.com/story/show/172424448).

I am going to close this issue out though.

- Aakash
