### ISSUE TITLE
CAPI `registry` configuration doesn't work for dockerhub.com

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/capi-k8s-release#23]
## Expected Behavior
I expect cf-push build pack to work with dockerhub.com registry since it is a publicly trusted registry.

## Actual Behavior
cf-push fails when using dockerhub.com as a cf-app registry. 

## Additional details
The configuration works for gcr.io but fails for dockerhub.com. See the following thread on details, steps, and possible solutions.

https://github.com/cloudfoundry/cf-for-k8s/issues/71

**Comment by jamespollard8** [comment]
Conversation has all been happening on cloudfoundry/cf-for-k8s#71
