### ISSUE TITLE
Suggested tweaks to CF for K8s configuration

### ISSUE THREAD

**Issue by pivotaljohn** [cloudfoundry/capi-k8s-release#24]
Greetings CAPI Friends!  We bring glad tidings from the Release Integration team.

While merging https://github.com/cloudfoundry/cf-for-k8s/pull/63, we noted a few items worth talking through but not so crucial as to block this PR.

1. Requirement: [reference the cnb image](https://github.com/cloudfoundry/capi-k8s-release/blob/332c231e9a8eb039b748a57d445e785e2d0c6b59/templates/cf-autodetect-clusterbuilder.yml#L7) using its SHA-256 digest
   - This affixes the version of the dependency:
      - ensures that regressions are not introduced indirectly
      - supports better chain-of-custody of assets incorporated into CF for K8s.
   - Note that [we created an overlay](https://github.com/cloudfoundry/cf-for-k8s/pull/63/commits/f03194728db0999f10bd062aa4d9814b405e5c4e) to pin to the `0.0.55-bionic` tag as a stopgap; please remove that overlay when you pin to the appropriate digest.
1. Suggestion: in [`config/values.yml`](https://github.com/cloudfoundry/cf-for-k8s/blob/bd7b4f6efba37e5eb418430cd270b06fcf8725fd/config/values.yml#L145) move `kpack` key underneath the `capi` key.
   - The `capi-k8s-release` component owns the `kpack` dependency.
1. Suggestion: review the value specified in the blobstore region (mentioned in [a conversation on #63](https://github.com/cloudfoundry/cf-for-k8s/pull/63#discussion_r391743155)).
1. Suggestion: until kpack is shown to be useable with DockerHub as its backing store, remove references to it in your [`README.md`](https://github.com/cloudfoundry/capi-k8s-release/blob/57a38b0355f27340de7c264774585ba20599a9ed/README.md).

Cheers!

----
cc: @cloudfoundry/cf-release-integration

**Comment by jamespollard8** [comment]
1. and 4. no longer appear relevant but 2. and 3. still seem worthwhile

**Comment by piyalibanerjee** [comment]
Made an update to change blobstore.region to be "" rather than "' '". Thanks for the suggestion!
