### ISSUE TITLE
`capi_kpack_watcher` and `nginx` images should be pinned

### ISSUE THREAD

**Issue by jamespollard8** [cloudfoundry/capi-k8s-release#26]
shoutout to Adrian for catching this

The unpinned images are [here](https://github.com/cloudfoundry/cf-for-k8s/blob/ada64d42c467cc96d64e984c16154f79c87d3523/config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values.yml#L7-L8)

>yeah we should totally do that
\- Selzo

**Comment by selzoc** [comment]
This is resolved as of https://github.com/cloudfoundry/cf-for-k8s/commit/45c291549a2a59e3f5a7f4668f3d5d44c4023478
