### ISSUE TITLE
please add an OSS license to the repo

### ISSUE THREAD

**Issue by beckettsean** [cloudfoundry/capi-k8s-release#31]
Howdy! There are some commercial products that want to package this repo, but cannot until there is an explicit license. It's legally dangerous for anyone to use your code without some form of license on the code. Most CF projects are Apache 2 licensed.

Thanks!

**Comment by jspawar** [comment]
Taken care of by this merged PR: https://github.com/cloudfoundry/capi-k8s-release/pull/30
