### ISSUE TITLE
[Bug] Retrying the ccdb-migration job thrice fails on AKS

### ISSUE THREAD

**Issue by sannidhi** [cloudfoundry/capi-k8s-release#35]
Reported by cf-for-k8s team cc:@jamespollard8

Install is now failing frequently on AKS (2/3 attempts so far)
see https://release-integration.ci.cf-app.com/teams/main/pipelines/cf-for-k8s/jobs/validate-azure/builds/14 and https://release-integration.ci.cf-app.com/teams/main/pipelines/cf-for-k8s/jobs/validate-azure/builds/16

```
8:45:54PM: ---- waiting on 6 changes [239/245 done] ----
8:45:58PM: ongoing: reconcile deployment/capi-api-server (apps/v1) namespace: cf-system
8:45:58PM:  ^ Waiting for 1 unavailable replicas
8:45:58PM:  L ok: waiting on replicaset/capi-api-server-5cc896b848 (apps/v1) namespace: cf-system
8:45:58PM:  L ok: waiting on podmetrics/capi-api-server-5cc896b848-p25vl (metrics.k8s.io/v1beta1) namespace: cf-system
8:45:58PM:  L ongoing: waiting on pod/capi-api-server-5cc896b848-p25vl (v1) namespace: cf-system
8:45:58PM:     ^ Condition Ready is not True (False)
8:45:58PM:  L ok: waiting on pod/capi-api-server-5cc896b848-mz7lt (v1) namespace: cf-system
8:45:58PM: fail: reconcile job/ccdb-migrate (batch/v1) namespace: cf-system

kapp: Error: waiting on reconcile job/ccdb-migrate (batch/v1) namespace: cf-system: finished unsuccessfully (Failed with reason BackoffLimitExceeded: Job has reached the specified backoff limit)
```

Background: The cc-db migration job has to wait until the database (postgres) is ready. As a workaround to this issue we added a retry policy which tries 3 times to run the migrations. Looks like it is failing on AKS so we should either increase the number of retries or have a more robust policy. 

Related story: https://www.pivotaltracker.com/story/show/172414069

**Comment by jamespollard8** [comment]
My suggested AC: we should be able to run 5 AKS deploy-smoketest-delete cycles without seeing a ccdb migration related deploy failure.

**Comment by davewalter** [comment]
@jamespollard8, @acosta11 and I were giving this some thought and wondered about the strategy of retrying the migration job up to three times. It seems like the thing that really needs to be retried is validation that the database is available and ready for use, which may take more than three attempts, depending on the speed of the cluster. Once that is confirmed, we suspect that you would only want the actual migration to be run once, regardless of whether it passed or failed. Retrying the migration does not seem like it would achieve a different outcome if the first attempt failed.

**Comment by jspawar** [comment]
@davewalter we do have a story to investigate approaches such as the ones you've suggested awaiting prioritization. Until then, I have bumped up the retry count to hopefully temporarily mitigate the flakiness you are all seeing in CI. (Story: https://www.pivotaltracker.com/n/projects/966314/stories/172414069)

Ran the following experiment 2-3 times:

```bash
for x in $(seq 10); do echo "--- deployment: #${x} ---" && kapp delete -a cf -y && ./bin/install-cf.sh aks-vals.yml 2>>failures.log ; done
```

Saw no failures to deploy any of these times. Pushed these changes up to `capi-k8s-release` and will PR into `cf-for-k8s`. 

@davewalter @jamespollard8 would you prefer to close this out for now knowing this is a known issue until the other story I linked above is completed? Or keep it open until that other story is delivered?

**Comment by jamespollard8** [comment]
We're okay with you maintaining your github issues however works best for you. We'll need to pickup this change in cf-for-k8s and then see several AKS validation runs in our CI before having a good sense of whether this resolves the issue.

**Comment by jspawar** [comment]
@jamespollard8 will keep this open for now until you get some runs through CI then. Thanks!

**Comment by jamespollard8** [comment]
This seems to have helped. Our pipeline is still failing but I'm no longer seeing any of the "waiting on reconcile job/ccdb-migrate" error.

I believe we're good to close this.

**Comment by sannidhi** [comment]
Thanks @jamespollard8 !
