### ISSUE TITLE
CAPI api server runs out of DB connections

### ISSUE THREAD

**Issue by KesavanKing** [cloudfoundry/capi-k8s-release#36]
The number of  DB connections is limited to 500 because of which can't able to scale capi-api-server.

Default max connections is set to 25  [here](https://github.com/cloudfoundry/capi-k8s-release/blob/b6ecc16c43a0b88da145c3c7b7b369052646cc35/templates/ccng-config.lib.yml#L117)
 I tried to scale capi-apiserver to 20 replicas and got the following error in pre-start init container

`Caused by:
PG::ConnectionBad: FATAL:  remaining connection slots are reserved for non-replication superuser connections`

Next tried  by changing max_connections to 100 and were able to scale only 5 replicas of capi-api-server.

---------
And other thing what observed is ,  even if one replica of api-server is down , API is not accessible. It gives `500` status code

> Error Code: 500
Raw Response: {}
FAILED

**Comment by KesavanKing** [comment]
We performed scale tests in which we pushed source code based apps. When we reach till 500 apps we could see lot of `500` responses . We suspect DB connections is the problem.

**Comment by KesavanKing** [comment]
Our scalability tests details can be found in https://github.com/perf-cfk8s/docs/wiki/cf-for-k8s-v0.1.0

**Comment by cwlbraa** [comment]
We'd really like to be able to increase the max connections on that postgres. Alternatively we could tune down the size of the connection pools.

**Comment by heycait** [comment]
Given the conversation around converging on a [shared CF on K8s vision](https://docs.google.com/document/d/1rG814raI5UfGUsF_Ycrr8hKQMo1RH9TRMxuvkgHSdLg), we won’t be focused on scaling the current cf for k8s and are going to close the issue.

We’d recommend either commenting on the document to discuss scaling needs or attending the Cloud Foundry for Kubernetes SIG meeting on the calendar here: https://www.cloudfoundry.org/community-calendar/
