### ISSUE TITLE
Env variables are not passed to kpack builds

### ISSUE THREAD

**Issue by kramerul** [cloudfoundry/capi-k8s-release#37]
### Summary

Some buildpacks [require environment variables](https://github.com/paketo-buildpacks/bellsoft-liberica#configuration) for configuration. But they are not passed to the [kpack build](https://github.com/pivotal/kpack/blob/master/docs/build.md#configuration)

As you can see [in the code](https://github.com/cloudfoundry/cloud_controller_ng/blob/a904b8dee962f9edfa143490d4530968b5598bce/lib/cloud_controller/kpack/stager.rb#L67-L80) no environment variables are passed.
### Reproduction Steps

Push a java application with *$BP_JAVA_VERSION=8.*"

### Expected behavior

_What was the expected result?_

The configuration variable is taken into account.

**Comment by ssisil** [comment]
Hi @kramerul  - we are addressing this issue with this story - https://www.pivotaltracker.com/story/show/172301179

**Comment by jkbschmid** [comment]
Hi @ssisil, I saw that the issue was solved in cc_controller_ng and that the story is closed. Only the cc_controller_ng image bump is missing. Is there a regular release schedule or an ETA ? :)

**Comment by ssisil** [comment]
@jkbschmid - Once we do acceptance on it and it makes it through our CI pipeline - the image should be bumped. Expect sometime this week.

**Comment by aashah** [comment]
This is now in cf-for-k8s. Closing this out.
