### ISSUE TITLE
Request Failed 404 from CAPI apiserver : Droplet not found : CF-ResourceNotFound 

### ISSUE THREAD

**Issue by KesavanKing** [cloudfoundry/capi-k8s-release#38]
We deployed cf-for-k8s and performed a scale tests . We pushed source code based apps. We reached till 800 apps . Under such high load we could  see the following error in capi-api-server
<pre>
{"timestamp":1587738150.8981497,"message":"Request failed: 404: {\"errors\"=>[{\"detail\"=>\"Droplet not found\", \"title\"=>\"CF-ResourceNotFound\", \"code\"=>10010, \"test_mode_info\"=>{\"detail\"=>\"Droplet not found\", \"title\"=>\"CF-ResourceNotFound\", \"backtrace\"=>[\"/cloud_controller_ng/app/controllers/v3/application_controller.rb:34:in `resource_not_found!'\", \"/cloud_controller_ng/app/controllers/v3/apps_controller.rb:347:in `droplet_not_found!'\", \"/cloud_controller_ng/app/controllers/v3/apps_controller.rb:322:in `current_droplet'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/abstract_controller/base.rb:194:in `process_action'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/rendering.rb:30:in `process_action'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/abstract_controller/callbacks.rb:42:in `block in process_action'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:132:in `run_callbacks'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/abstract_controller/callbacks.rb:41:in `process_action'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/rescue.rb:22:in `process_action'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:168:in `block in instrument'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:168:in `instrument'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/instrumentation.rb:32:in `process_action'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/abstract_controller/base.rb:134:in `process'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionview-5.2.4.2/lib/action_view/rendering.rb:32:in `process'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal.rb:191:in `dispatch'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal.rb:252:in `dispatch'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/routing/route_set.rb:34:in `serve'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/journey/router.rb:52:in `block in serve'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/journey/router.rb:35:in `each'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/journey/router.rb:35:in `serve'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/routing/route_set.rb:840:in `call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/tempfile_reaper.rb:15:in `call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/http/content_security_policy.rb:18:in `call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:98:in `run_callbacks'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/callbacks.rb:26:in `call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'\", 
\"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-
5.2.4.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/executor.rb:14:in `call'\", 
\"/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'\", 
\"/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/urlmap.rb:74:in `block in call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/urlmap.rb:58:in `each'\", 
\"/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/urlmap.rb:58:in `call'\", 
\"/cloud_controller_ng/middleware/request_logs.rb:22:in `call'\", 
\"/cloud_controller_ng/middleware/security_context_setter.rb:19:in `call'\", \"/cloud_controller_ng/middleware/vcap_request_id.rb:15:in `call'\",
 \"/cloud_controller_ng/middleware/cors.rb:49:in `call_app'\", 
\"/cloud_controller_ng/middleware/cors.rb:14:in `call'\", 
\"/cloud_controller_ng/middleware/request_metrics.rb:12:in `call'\", 
\"/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/builder.rb:244:in `call'\", 
\"/usr/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'\", 
\"/usr/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'\", 
\"/usr/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'\", 
\"/usr/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'\", 
\"/usr/local/lib/ruby/gems/2.5.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in `block in 
spawn_threadpool'\"]}}]}","log_level":"info","source":"cc.api","data":{"request_guid":"3b75e731-1246-
4c94-b2a0-b7300d9359e7::02a69280-4037-4b1a-bec8-
aef5a674c325"},"thread_id":47075637335140,"fiber_id":47075631752220,"process_id":1,"file":"/cloud_c
ontroller_ng/app/controllers/v3/application_controller.rb","lineno":178,"method":"handle_exception"}
</pre>

cf-for-k8s Version:  https://github.com/cloudfoundry/cf-for-k8s/releases/tag/v0.1.0

**Comment by aashah** [comment]
Hey @KesavanKing,

Looks like there are a couple issues you've observed while scaling cf-for-k8s. Was wondering if you could share some of the steps folks on our team can take to reproduce some of these scale tests. Information like the size of our cluster, IAAS, instance types, any custom overlays...etc.

Thanks!

**Comment by KesavanKing** [comment]
@aashah  , Thanks for the reaching out. We have created a page where we captured our tests setup, and all relevant details https://github.com/perf-cfk8s/docs/wiki/cf-for-k8s-v0.1.0

Hope this might help you to reproduce.

**Comment by sannidhi** [comment]
Hi @KesavanKing,

Thank you for your patience as we get around to doing performance tests on our team. I wanted to follow-up on this issue as its been a while and see that it was reported on v0.1.0. A lot has changed since v0.1.0 particularly around storing packages in a registry instead of a blobstore. In the past we have seen the kind of errors mentioned here when there are issues downloading from the blobstore. 

We also currently have 2000 apps in our performance environment but have not seen this error - it would help a lot if you can document additional info for the types of app, registry used, iaas etc so that we can reproduce on our end. Have you seen the droplet not found error with the with the newer version v1.0.0? If yes, can you provide updated logs so we can update this issue and take a look? 

Thank you for reporting this bug, looking forward to your reply.

**Comment by KesavanKing** [comment]
Hi Sannidhi,

Thanks for the consideration.
In our recent scale tests on v1.0.0 , we didn't face this issue. So we can close it safely.
