### ISSUE TITLE
capi-k8s-release should follow cf-for-k8s best practices for generating, storing, and reading secrets

### ISSUE THREAD

**Issue by cwlbraa** [cloudfoundry/capi-k8s-release#56]
see [Credhub and cf-for-k8s Password Generation](https://docs.google.com/document/d/1VKMVaBcIUjro_y38KwMskvqoqSXljqVcLA_CVPTHbXU/edit#)

We need to make an effort to get capi-k8s-releases' secrets out of its big global configmap. Part of doing this will be removing unnecessary TLS certificates out of capi-k8s-release, but there are more secrets hiding in the configmap:

- https://github.com/cloudfoundry/cf-for-k8s/issues/228 CAPI UAA client secret is stored as a plain text in value in cloud-controller-ng-yaml configmap
- https://github.com/cloudfoundry/cf-for-k8s/issues/227 The CC blobstore access key is stored as a plain text value to cloud-controller-ng-yaml configmap
- https://github.com/cloudfoundry/cf-for-k8s/issues/226 The CC database password is passed as a plain text value to cloud-controller-ng-yaml config 
- https://github.com/cloudfoundry/cf-for-k8s/issues/225 UAA client password is passed as a plain text to `cf-api-kpack-watcher`

I think we'd also need to handle the database encryption keys.

**Comment by Syerram** [comment]
@cwlbraa The database encryption key for CAPI is now available as secret `capi-database-encryption-key-secret`. The native secret is on cf-for-k8s master.

Following are the native secret names are available in cf-for-k8s
[cf-for-k8s#225](https://github.com/cloudfoundry/cf-for-k8s/issues/225) - `kpack-watcher-client-secret`
[cf-for-k8s/issues/226](https://github.com/cloudfoundry/cf-for-k8s/issues/226) -`capi-database-password`
[cf-for-k8s/issues/227](https://github.com/cloudfoundry/cf-for-k8s/issues/227) - `capi-blobstore-secret-key`
[cf-for-k8s/issues/228](https://github.com/cloudfoundry/cf-for-k8s/issues/228) - `cloud-controller-username-lookup-client-secret`

Let us know if you have any questions

**Comment by cwlbraa** [comment]
done in 3 stories:

eirini certs: https://www.pivotaltracker.com/story/show/173905990
capi: https://www.pivotaltracker.com/story/show/173973874
cf-api-controllers: https://www.pivotaltracker.com/story/show/173973896
