### ISSUE TITLE
Nginx `client_max_body_size`

### ISSUE THREAD

**Issue by kramerul** [cloudfoundry/capi-k8s-release#6]
We tried to use this helm chart together with quarks.

While running a `cf push` it turned out that the nginx configuration is not capable to forward requests with sizes which exceeds 1MB.

Therefore it's necessary to add the the `client_max_body_size` configuration value.

```
location / {
  client_max_body_size       100m;
  access_log  /cloud_controller_ng/nginx-access.log;
  ...
```

**Comment by emalm** [comment]
@ssisil @selzoc @cwlbraa would y'all take a PR to add this nginx config? /cc @bkrannich

**Comment by cwlbraa** [comment]
absolutely yes! it bears mentioning that `cf push` will also fail due to the lack of an upload module being compiled in - but yes, I'd gleefully merge this as a PR.

**Comment by loewenstein** [comment]
@cwlbraa what's the eta for `cf push` on k8s? Backlog-wise I suppose [Run a droplet that was built with kpack on k8s](https://www.pivotaltracker.com/story/show/169924245) is the major missing piece?

We'll soon look into `cf login` with the k8s manifests from capi and uaa, opening issues and/or PRs if we find anything.

**Comment by cwlbraa** [comment]
@loewenstein its chugging along, and yes that story was one major piece. this is the placeholder that we keep breaking incremental stories out of: https://www.pivotaltracker.com/story/show/169404061

**Comment by piyalibanerjee** [comment]
Hi @kramerul and @loewenstein - cf push on k8s should be working now! Please let us know if you run into any issues.
