### ISSUE TITLE
[RFC #0001] Supporting service bindings used during staging

### ISSUE THREAD

**Issue by jspawar** [cloudfoundry/capi-k8s-release#62]
**Feature Name:** Supporting service bindings used during staging in cf-for-k8s

**Type:** feature

**Author:** CAPI team

**Related components:** cloud_controller_ng, capi-k8s-release

## Summary

We create a Service Binding Controller to manage Service Bindings.

## Motivation
We currently provide service bindings to apps at build-time via the `VCAP_SERVICES` environment variable. This mechanism is not supported by the Paketo Cloud Native Buildpacks.

We need to continue to support build-time service bindings so that the platform can continue to automatically configure APM integrations on behalf of apps. This will require providing the service binding to kpack as a [Kubernetes Service Binding.](https://github.com/k8s-service-bindings/spec) This type of service binding takes the form of a structured directory, mounted to the build container.

## Proposal

When the service binding /create endpoint is hit, CAPI will create a Service Binding resource.  The controller will call back to CAPI with the state of that service binding whenever it changes. When CAPI will include a reference to that resource when it requests new builds from kpack, and when it requests long-running processes (LRPs) from Eirini.

## Drawbacks

This may require some work from Eirini to actually mount the secret to the running image.

This adds another codebase and component that will need to be managed.

There's currently no endpoint for updating a service binding. We don't know why.

## Alternatives

We could imperatively create service bindings. In that case CAPI would need to monitor and manage the status of the service binding resources and synchronize its data state according.

## Notes

We're not sure what the failure modes are for service binding creation/management, and probably need to investigate that further.

As of this writing (August 18 2020) kpack does not support the Kubernetes service binding spec, it supports the CNB service binding spec. We expect it to support the Kubernetes spec soon, since the CNB spec is already deprecated.

Placeholder tracker stories
[[PLACEHOLDER] mount service bindings to runtime container](https://www.pivotaltracker.com/story/show/174365964)
[[PLACEHOLDER] convert VCAP_SERVICES to kpack bindings at build time](https://www.pivotaltracker.com/story/show/174365679)

**Comment by njbennett** [comment]
Updated this to remove WIP status, reflect our latest thinking. We expect to be picking this work up in about a month.

**Comment by mkocher** [comment]
I understand* the need for build packs to know which services are bound to an application, but it has always bothered me that a build process would be given live credentials. I’d like to see this change result in build packs being given the bound services without credentials to them.

* I’ve never really liked it though, and think it represents some debt. Push-then-bind results in a different output than bind-then-push. So it’s something a developer has to know that is not obvious. Maybe this got better in v3? My mental model is still v2 based.

**Comment by tcdowney** [comment]
> When the service binding /create endpoint is hit, CAPI will create a Service Binding resource. **The controller will call back to CAPI with the state of that service binding whenever it changes.**

Can we elaborate on what this means? What state changes will the controller be tracking and what will Cloud Controller need to be aware of?

**Comment by piyalibanerjee** [comment]
@tcdowney -- that part is unclear now since we don't know exactly how the new kpack service bindings will track the status of the bindings. We will know more once the new kpack binding is released in 3-6 weeks.

**Comment by njbennett** [comment]
@mkocher 

That's a really interesting point. And I think should be technically possible. The buildpack detect scripts key off of the service binding's `type`. We'll have to look into what other information they need and under what circumstances.

As far as I know the big thing that service-bind-at-build-time enables modifying the Java startup command with configuration necessary to connect to an agent, which is a common pattern for monitoring. Maybe there's another place besides staging where we could modify startup commands (and provide agent binaries) but that seems out of scope for this particular conversation. Might be worth recording in the RFC though because no one on the team understood this in detail when we started this exploration.

**Comment by tcdowney** [comment]
@jspawar you'll be happy to know the dream lives on: https://github.com/cloudfoundry/cf-k8s-controllers/issues/463

**Comment by jspawar** [comment]
@tcdowney wowow, good job y'all
