### ISSUE TITLE
ruby app fails to start with 'bundle: not found' error

### ISSUE THREAD

**Issue by kieron-dev** [cloudfoundry/capi-k8s-release#72]
We've noticed this attempting to deploy postfacto on cf-for-k8s v0.6.0.

Steps to reproduce:

1. Unzip postfacto package from https://github.com/pivotal/postfacto/releases/download/4.3.0/package.zip
1. Modify `package/cf/manifest.yml` to remove the buildpacks and services lists
1. Remove the line with `ruby '2.6.3'` from `package/assets/Gemfile
1. `cd package/cf`
1. `./deploy.sh app-name`

Staging completes successfully, but the app fails to start. Logs on the app container show `/bin/sh: 1: bundle: not found`.

If you remove `command` from the `package/cf/manifest.yml`, and instead create `package/assets/Procfile` with contents `web: bundle exec rake db:migrate && bundle exec rails s -p \$PORT -e development`, the app will start (although that also requires configuring the app to use mysql and redis correctly. Without that, at least you'll see bundle is found).

Slack thread: https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1600788157043700

cc: @cloudfoundry/eirini

**Comment by cwlbraa** [comment]
additional context on CNBs and command overrides: https://cloudfoundry.slack.com/archives/CUWG5TXB5/p1600789507001400

it sounds like we can maintain the launcher environment by overriding "args" instead of "command", but Eirini may only let us override "command".

**Comment by cwlbraa** [comment]
Even with changes to eirini, I think to fix this we'd likely have to make CC aware of the difference between docker and kpack droplets?

**Comment by cwlbraa** [comment]
https://github.com/cloudfoundry/cf-for-k8s/issues/502 < second issue for visibility

**Comment by piyalibanerjee** [comment]
From IPM: We may approach this by making a class specifically for this rather than adding conditional logic to an existing lifecycle class.

**Comment by piyalibanerjee** [comment]
Hello @kieron-dev - we fixed the original issue and are no longer seeing the "bundle: not found" error. The example app you provided is still crashing, however, possible due to a different issue. The rake is aborting due to this error: "ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime.".
