### ISSUE TITLE
[RFC #0002] Interacting with OCI Image Registries from cloud_controller_ng

### ISSUE THREAD

**Issue by jspawar** [cloudfoundry/capi-k8s-release#74]
**Feature Name:** Interacting with OCI Image Registries from cloud_controller_ng

**Type:** Feature

**Author:** CAKE team

**Related components:** cloud_controller_ng, capi-k8s-release

## Summary

In cf-for-k8s we are now using an OCI image registry to store package uploads instead of a blobstore (see: https://github.com/cloudfoundry/cf-for-k8s/issues/409). Currently only package uploads are supported, and other workflows such as [deleting a package](https://v3-apidocs.cloudfoundry.org/version/3.89.0/index.html#delete-a-package) and [copying a package](https://v3-apidocs.cloudfoundry.org/version/3.89.0/index.html#copy-a-package] are unsupported.

Our initial goal is to support package deletes, but it would be nice if our solution is general enough to support other operations. At the minimum it should also support copying packages, but we suspect we might need to also support operations on droplets (e.g. deleting a droplet should delete the image in the registry).

## Motivation

1. Prevent disk usage in the registry from growing unbounded
1. Currently the background jobs around deleting package “blobs” fail and will result in errors, we want them to succeed!

### Update the package-image-uploader

The package-image-uploader is a micro-service that uses the [go-containerregistry](https://github.com/google/go-containerregistry) package[1] to interact with the OCI registry. Currently, it’s deployed as a container in the cf-api-server pods and is used for converting an uploaded zip file into a container image that is uploaded to the registry.

We propose that we enhance (and rename) the package-image-uploader to support other operations by adding additional endpoints for deleting, copying, etc.

We propose the following means of deploying this new flavor of the package-image-uploader:
1. As a container colocated with each pod that needs it and is only exposed on localhost
    * Leaning towards this
1. As a separate pod
1. Leaving it on the `cf-api-server` pod and exposing its port to other pods

## Benefits
* We have already done the scaffolding for the Go server for this
* It is already configured to work with the same credentials that we use with kpack
* It uses the go-containerregistry library[1] 🙂  
* CCNG is already structured in a way that lends itself to preferring to interact with external services for operations regarding/surrounding app packages (e.g. needing to talk to an external blobstore service, the bits service)
* Wouldn’t have to take on any additional operational complexity in our automation to figure out how to to package and deploy some new thing
    * This is because we’re already building the package-image-uploader image from source with a buildpack and it’s a pretty simple+straightforward process

## Drawbacks
* We need to make it accept requests from other Pods (currently it only listens on localhost)
    * This is only a drawback if we don't colocate the container with all pods that need it
* We need to add security so that only Pods we trust can hit its endpoints
    * This is only a drawback if we don't colocate the container with all pods that need it

### Write our own Ruby client for the OCI registry and use it in CCNG’s code
We could write our own client for the OCI registry that does what we need to do.

**Benefits:**
* This client would be tailored entirely to our needs
* We could invoke it as needed from the Ruby code in CCNG
* Wouldn’t have to take on any additional operational complexity in our automation to figure out how to to package and deploy some new thing
    * This is because we’re already building the CCNG image from source with a buildpack and it’s a pretty simple+straightforward process

**Drawbacks:**
* The OCI Registry API is non-trivial, we’d have to develop expertise in integrating with it
* We would need to figure out how to support the same authentication mechanisms that kpack supports
* This could require a lot of development work since we would have to reimplement everything ourselves
* We’d be directly responsible for integration testing this client we make against multiple, real OCI registries
    * Would have to make something like our blobstore fanout tests but with OCI registries and we probably don’t want another of those
    * Using a library somebody else maintains offloads a lot of this burden of testing to those library maintainers

### Use a Ruby gem for interacting with the OCI registry 
We could use a gem like https://github.com/deitch/docker_registry2 to interact with the registry from within the CCNG codebase.

**Benefits:**
* We already support switching the blobstore client we use (fog vs webdav). We could write a similar registry one that implements the “blobstore client interface” and use this.
* Wouldn’t have to take on any additional operational complexity in our automation to figure out how to to package and deploy some new thing
    * This is because we’re already building the CCNG image from source with a buildpack and it’s a pretty simple+straightforward process

**Drawbacks:**
* The gem is _mostly_ unsupported
* The gem technically implements the Docker Registry v2 API spec, it is unclear to us how much this diverges from the OCI Registry API spec
    * Maybe this doesn’t matter for deletes?
    * Could matter if we want to use a similar mechanism for copying packages
* The gem may require credentials to be provided differently from what kpack (which uses https://github.com/google/go-containerregistry)[1] supports
            * It appears to only support password-based authentication
    * This could make it difficult to support other authentication methods in the future

### Shell out to a binary utility that uses [go-containerregistry](https://github.com/google/go-containerregistry) to interact with the OCI registry from CCNG’s code
We write a Golang utility that leverages the https://github.com/google/go-containerregistry library[1]. Cloud Controller can shell out to this binary when interacting with the registry in places that it would interact with the blobstore.

**Benefits:**
* We shell out to binaries in other places… mainly when zipping and unzipping files.
* This could be operationally simpler than an additional micro-service
* Don’t need to worry about authentication to the service or troubleshooting it separately
* It uses the go-containerregistry library[1] 🙂

**Drawbacks:**
* We already have the package-image-uploader running as a container on the cf-api-server deployment. It knows how to upload images to the registry and could be enhanced to do other operations.
    * We would need to enhance this to accept requests on non-localhost
    * We would need to add some security mechanisms (NetworkPolicy + Istio AuthorizationPolicy could suffice), right now it accepts requests from anything since it is only reachable from within the cf-api-server Pod
* Compiling and packaging this binary into our images is going to be far from trivial with or without using buildpacks to compile our CCNG image
    * This is one of the main reasons we made the package-image-uploader in fact
* Shelling out to a binary could make it more difficult to surface errors to the user
    * Managing children processes is also generally a hassle (e.g. tracking PIDs, figuring out when processes are stuck, parsing their output, etc.)

## Notes
1. This library is often called out since it is the most preferred means of interacting with an OCI registry and OCI image since we have over time, through usage in our projects (e.g. cf-api-controllers) and other CF-related projects (e.g. kpack, lifecycle), to be the most comprehensive library which implements the OCI spec

**Comment by matt-royal** [comment]
There's an additional option: colocate the package-image-uploader as a container in the worker pod and only allow traffic from local-host. That's more or less exactly what we did with the local worker, and it sidesteps the security concerns since the server is only reachable from localhost.

**Comment by tcdowney** [comment]
I like that suggestion, @matt-royal, since it will allow us to sidestep the authorization issue. 👍  I'm worried that using `NetworkPolicy` alone isn't sufficient and I don't want to couple us too tightly with Istio `AuthorizationPolicy`.

**Comment by tcdowney** [comment]
## Context on this decision

We went through with the proposal and renamed the `package-image-uploader` into the `registry-buddy`. It is now a more generic mediator between Cloud Controller and the OCI Image Registry. We've implemented registry deletes on it (https://github.com/cloudfoundry/capi-k8s-release/pull/76) and _if_ we decide to implement any other classic Cloud Controller blobstore operations using the OCI registry we will further enhance the `registry-buddy` to do them on Cloud Controller's behalf.
