### ISSUE TITLE
/v3/processes/PROCESS_GUID returns incorrect process command

### ISSUE THREAD

**Issue by njbennett** [cloudfoundry/capi-k8s-release#79]
The BARA "setting_process_commands manifest and Procfile/detected buildpack command interactions prioritizes the manifest command over the Procfile and can be reset via the API" [fails when it checks that the process command has been set correctly.](https://github.com/cloudfoundry/capi-bara-tests/blob/73f823d7477ad95fdfac41be1994a7254adbc97f/baras/commands.go#L86)

It returns just the first argument in the command, in this case, "bundle" instead of "bundle exec rackup..." For multi-argument commands it should return the entire command.

The app works fine, so we're reasonably sure the problem is a display problem and the underlying process command is set correctly.

**Comment by tcdowney** [comment]
This ended up being the same as https://github.com/cloudfoundry/capi-k8s-release/issues/88 and was resolved by https://github.com/cloudfoundry/capi-k8s-release/pull/90.
