### ISSUE TITLE
[RFC #0003] Scheduling workloads across multiple k8s Namespaces

### ISSUE THREAD

**Issue by cwlbraa** [cloudfoundry/capi-k8s-release#83]
**Feature Name:**  Scheduling workloads across multiple k8s Namespaces

**Type:** feature

**Author:** Connor Braa

**Related components:** cloud_controller_ng, capi-k8s-release, eirini

## Summary

We plan to introduce a `/v3/placements` API. A single `placement` resource describe a namespace or namespaces where CF API workloads may be scheduled. Upon introduction, there will be an initial default placement for existing workloads. `/v3/placements` will likely be persisted in the k8s API as a `Placement` CRD. The placements API will provide future flexibility so that we may eventually support:

1. Dynamic, per-`/v3/space` kubernetes `Namespace` creation and deletion
2. Namespaces in other k8s clusters (Multicluster CF API)
3. Multiple namespaces in a single placement (Multicluster CF Apps)

## Motivation

Currently, the CF API schedules all of its runtime workloads into a 1-per-installation "cf-workloads" namespace via Eirini's OPI `LRP` API and the cf-k8s-networking `Route` CRD. All build-time workloads are scheduled into a different, 1-per-installation "cf-workloads-staging" namespace via Kpack's `Image` CRD. 

Recently, the Eirini team has added the capability to schedule `LRP` workloads across different namespaces. This is available both in OPI and k8s-natively in the new, as-of-yet unused `LRP` CRD. 

cf-for-k8s' first deployers and tire kickers have made explicit requests that apps don't all share one global k8s "cf-workloads" namespace. That global namespace is a bit of a security threat and could present a significant hurdle in the future when we want to give users more k8s API access. 

Some amount of initial thought has been given to how the CF API might benefit users that need to [schedule workloads across k8s clusters](https://docs.google.com/document/d/1INyD61z6v_pfN-IGgDwWCaylMWWuMyqvpN3r4_duPGo/edit?ts=5dc5e9b1#heading=h.tstaxw1unff1). I'd like to propose that we use namespaces as a way of exploring API modeling around workload placement broadly with the hopes that we'll later extend these same API resources to work across k8s clusters.

## Proposal

At a high level, I'd like to propose that we solve this problem through flexible, configurable data modeling. 

To give platform engineers the ability to place workloads in different Namespaces, one approach is to begin by creating a representation of the current state of workload placements. What follows are example objects that would represent the current way Apps, Routes, and Kpack Images are spread across Namespaces in cf-for-k8s. 

```json
resources: [
{
  "name": "existing-cf-for-k8s-placement",
  "guid": "placement-x",
  "targets": [
    {
       "namespace": "cf-workloads"
    }
  ],
  "global_runtime_default": true,
  "global_staging_default": false,
  "metadata": { "labels": {}, "annotations": {}}
},
{
  "name": "existing-cf-for-k8s-staging-placement",
  "guid": "placement-y",
  "targets": [
    {
       "namespace": "cf-workloads-staging"
    }
  ],
  "global_default": false,
  "global_default_staging": true,
  "metadata": { "labels": {}, "annotations": {}}
}
]
```
And the associated CRs that platform engineers could configure at deploy-time:
```yaml
---
apiVersion: apps.cloudfoundry.org/v1alpha1
kind: Placement
metadata:
  labels: 
     apps.cloudfoundry.org/placement_guid: placement-x
  annotations: {}
  name: existing-cf-for-k8s-placement,
  namespace: cf-system
spec:
  targets:
  -  namespace: cf-workloads
  global_runtime_default: true
  global_default_staging: false
---
apiVersion: apps.cloudfoundry.org/v1alpha1
kind: Placement
metadata:
  labels:
     apps.cloudfoundry.org/placement_guid: placement-y
  annotations: {}
  name: "existing-cf-for-k8s-placement",
  namespace: cf-system
spec:
  targets:
  -  namespace: cf-workloads
  global_runtime_default: false
  global_default_staging: true
```

A single placement describes a sort of multiplexer for CF Apps. In the initial, single-target case this multiplexer passes its inputs straight through to the underlying namespace. In the future, we'd want to support multi-target placements where the multiplexer would create copies of compute and networking resources across its targets. A single-process, routable web app in a space with a 2-target placement would have 2 "web" processes that map to two StatefulSets across 2 namespaces. Likewise, the app's associated Route would need to span those two namespaces or have copies in both. 

Once these API resources exist, we can add features to them. Examples that fit pretty naturally into this modeling include:

- A platform engineer wants the API to create and use independent Namespaces for each created `/v3/space`
  - This would likely be a something we could enable via CF API configuration at startup
- A platform engineer wants to have one space deploy to a specific, pre-existing Namespace
- Commercial CF packagers want some apps to be deployed to the `cf-system` Namespace
- A platform engineer wants to give devs the capability to deploy to an independent cluster for compliance reasons
   - Or wants to enforce that all apps in a given space deploy to that cluster
   - CF could feasibly deploy to clusters where it's a "guest" in a single namespace without elevated permissions.
- A platform engineer wants to give devs the capability to deploy across independent clusters for availability reasons
   - Or wants to enforce that all apps in a given space deploy across clusters

## Drawbacks

It's possible that modeling namespaces as part of (multicluster) workload placement is putting the cart before the horse and coupling together two concepts that don't necessarily need to be related. 

Features that might be a bit hairier to build with this modeling include:

- A platform engineer wants to move all workloads out of a certain namespace or cluster so it can be safely deleted
    - Modifying a Placement's spec in-place seems dangerous and difficult to reconcile
- An app developer wants to `cf scale appName -i 5` their app and understand where those instances will be placed

### Spaces have a Namespace, no "placements" required

Placements are not entirely necessary to get users' apps into separate namespaces. Instead, we could have the CF API and associated controllers create a Namespace for each new space and immediately start scheduling new app workloads into them. 

#### Spaces with "namespace" property

Rather than migrating or modeling placements independently of existing tenancy constructs, spaces could have a "namespace" field. This field would be seeded to "cf-workloads" for existing spaces, configurable upon space creation, and dynamically allocated when omitted. 

This option offers similar configurability as placements and backwards compatibility with the existing structure, but is flexible for future enhancements.

#### Migrate apps from global namespace to segmented namespace

To move them without user intervention, we'd need to find a way to safely move StatefulSets and Routes across Kubernetes namespaces during a cf-for-k8s deployment or the upgrade would incur app downtime or even breakage. 

### Orgs have a Namespace

This approach creates a situation similar to isolation segments, and would perhaps alleviate the need for dynamic namespace allocation. There's a similar solution space to be explored about migrating or not migrating existing apps. 

#### 

## Notes

TBD

**Comment by heycait** [comment]
Closing this out due to inactivity. We can revisit this in the future if needed.
