### ISSUE TITLE
ccdb-migrate job should not wait for Istio

### ISSUE THREAD

**Issue by mike1808** [cloudfoundry/capi-k8s-release#87]
Since upgrading Istio in cf-for-k8s to 1.7 and closing [cloudfoundry/cf-for-k8s#189](https://github.com/cloudfoundry/cf-for-k8s/issues/189) app containers should not start while the sidecar container is initializing, so there is no need for having custom code for that.

Also, with the current plan of supporting Istio and Contour without Istio ccdb-migrate should not rely at all that sidecar will be injected.

**Comment by tcdowney** [comment]
@mike1808 based on the [concerns on the Istio issue](https://github.com/istio/istio/pull/24737#issuecomment-660274460) around this using undocumented aspects of the Kubernetes Pod start-up process are you confident that Istio will be able to maintain this behavior?

I always considered their "fix" here to be less of a fix and more of a best-effort mitigation. I'm worried that across Istio upgrades (y'all test this so it's probably less risky) and Kubernetes versions this behavior might change and we'll have to add the check back in.

Maybe there is a way we can have the migrator task check if the `istio-proxy` sidecar container exists and iff it exists wait for it to become healthy.

**Comment by cwlbraa** [comment]
> Maybe there is a way we can have the migrator task check if the istio-proxy sidecar container exists and iff it exists wait for it to become healthy.

Alternatively, it could retry-until-short-timeout to log in to the database, regardless of what errors it sees when it's trying to connect. That behavior would be correct and istio-agnostic.

**Comment by tcdowney** [comment]
Yeah, that's a better idea!

**Comment by mike1808** [comment]
Currently, this issues blocks @cloudfoundry/cf-for-k8s-networking  team from merging Contour work to develop in cf-for-k8s.

**Comment by matt-royal** [comment]
> > Maybe there is a way we can have the migrator task check if the istio-proxy sidecar container exists and iff it exists wait for it to become healthy.
> 
> Alternatively, it could retry-until-short-timeout to log in to the database, regardless of what errors it sees when it's trying to connect. That behavior would be correct and istio-agnostic.

One simple way to do this: make a new rake task that spins until it can connect to the DB (and may eventually time out). The ccdb migrate job can then run `rake spin-until-db-connects EXISTING_RAKE_TASKS`

**Comment by matt-royal** [comment]
I have a branch that replaces the istio-specific logic with generic logic that waits for a DB connection to be available before running the migrations. However, it looks like we still need to explicitly kill the istio sidecar as part of the job, as the istio-proxy is still running after the run-migrations container completed. Is this expected?

**Comment by tcdowney** [comment]
Yeah, unfortunately for `Jobs` you have to explicitly kill it with that `/quitquitquit` endpoint. The hope is that this can be confused if/when Kubernetes ever gets something like first-class Sidecar containers (https://github.com/kubernetes/enhancements/issues/753), but right now it's kinda rough.

This Istio issue talks more about it:
https://github.com/istio/istio/issues/11659

**Comment by tcdowney** [comment]
This is fixed now on the latest cf-for-k8s `main`. See:
* https://github.com/cloudfoundry/cloud_controller_ng/commit/d7a5fe3cbce5e111befe72dae7d9496d9fd66881#diff-8e48e5cccab8a9fc9d245274271c1c1f0065248b0cd44539a08dc6aeca0f39a1
* https://github.com/cloudfoundry/cloud_controller_ng/commit/56ee90b53cf706b19105aa3fd48b845e4d473a70#diff-8e48e5cccab8a9fc9d245274271c1c1f0065248b0cd44539a08dc6aeca0f39a1
* https://github.com/cloudfoundry/cloud_controller_ng/commit/b8aa9c40f7c5b209709a1f629659712bbc11153b#diff-8e48e5cccab8a9fc9d245274271c1c1f0065248b0cd44539a08dc6aeca0f39a1

Thanks for reporting this @mike1808 ! 🙂
