### ISSUE TITLE
Readiness probe for ccng workers and registry-buddy are not working

### ISSUE THREAD

**Issue by mike1808** [cloudfoundry/capi-k8s-release#91]
Currently, all pods except cf-api-server have TCP readiness probes. They are not working properly because of few reasons:

1. The probe are listening for `127.0.0.1`. However, Kubernetes uses PodIP:port to reach probe, so if the server listens on `127.0.0.1` they won't accept connections from outside.
2. The probes for ccng jobs stop working when the job finished. When it happens Kubernetes will pods not ready.

To deploy cf-for-k8s without Istio you can deploy [cf-for-k8s#contour-ingress](https://github.com/cloudfoundry/cf-for-k8s/tree/contour-ingress) branch in a standard way and ensure that [networking.ingress_solution_provider](https://github.com/cloudfoundry/cf-for-k8s/blob/contour-ingress/sample-cf-install-values.yml#L23) is set to `contour` (should be a default in that branch).

**Comment by mike1808** [comment]
We've tried to change the listen address for registry-body to `0.0.0.0` and it works ok.
https://github.com/cloudfoundry/capi-k8s-release/blob/master/src/registry-buddy/main.go#L55

However, for CCNG, even after changing the address here https://github.com/cloudfoundry/cloud_controller_ng/blob/master/lib/cloud_controller/background_job_environment.rb#L30 we could make pods work because the probes stop listening after they finish.

**Comment by tcdowney** [comment]
@mike1808 do you have steps for deploying cf-for-k8s without Istio that we can follow?

**Comment by mike1808** [comment]
@tcdowney sure. I forgot to mention. I'll update the issue.

**Comment by mike1808** [comment]
@tcdowney also. [This overlay](https://github.com/cloudfoundry/cf-for-k8s/blob/contour-ingress/config/ingress/common/remove-capi-readiness-probes.yaml) removes CAPI readiness probes. Make sure to delete it if you want to test them.

**Comment by tcdowney** [comment]
@mike1808 one other thing I just realized... making `registry-buddy` listen on `0.0.0.0` is actually **not** something we want to do. It's security model is contingent on it only being accessible internally.. ideally it would even use a unix socket instead of the loopback address.

So making it listen on `0.0.0.0` is not an option... I'm guessing this means we cannot use a TCP healthcheck in this way?

**Comment by mike1808** [comment]
@tcdowney you're right. TCP readiness probes are checked via podIP:port, so if you don't accept connections on podIP you cannot use them.

**Comment by tcdowney** [comment]
I needed to pick up some changes from `main` on cf-for-k8s so rebased the Contour branch and pushed to here:
https://github.com/cloudfoundry/cf-for-k8s/compare/contour-ingress-rebased

**Comment by heycait** [comment]
This has been included here: https://github.com/cloudfoundry/cloud_controller_ng/pull/1975
